# Generated by Django 2.2.16 on 2020-10-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_ocurrencereport_commited_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocurrencereport',
            name='last_of_day',
            field=models.BooleanField(default=False),
        ),
    ]
