# Generated by Django 2.2.16 on 2020-10-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_ocurrencereport_last_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocurrencereport',
            name='app_name',
            field=models.CharField(default='undetermined', max_length=20),
        ),
    ]
