# Generated by Django 2.2.16 on 2020-10-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_ocurrencereport_app_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ocurrencereport',
            unique_together={('commit', 'app_name')},
        ),
    ]
